mutation SEND_CONTACT_REQUEST(
	$subjectId: ID!
	$customerName: String!
	$customerEmail: String!
	$description: String!
) {
	sendContactRequest(
		subjectId: $subjectId
		customerName: $customerName
		customerEmail: $customerEmail
		description: $description
	) {
		id
	}
}
