mutation CREATE_USER_ACCOUNT(
	$displayName: String!, 
	$emailAddress: String!, 
	$password: String!,
  $reCaptchaToken: String!) 
{
  createUserAccount(
		displayName: $displayName, 
		emailAddress: $emailAddress, 
		password: $password,
    reCaptchaToken: $reCaptchaToken
	) {
    id
    displayName
    lastLogin
    emailAddress
    emailLastVerificationSent
    passwordLastUpdated
    isDisabled
  }
}