mutation USER_LOGIN($emailAddress: String!, $password: String!, $extended: Boolean) {
  login(emailAddress: $emailAddress, password: $password, extended: $extended) {
		id
    displayName
    lastLogin
    avatarColor
    emailAddress
    isEmailVerified
    emailLastVerificationSent
    passwordLastUpdated
    createdAt
  }
}
